// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwbmgjotyqldlmhwjrji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3Ym1nam90eXFsZGxtaHdqcmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDg2NjAsImV4cCI6MjA3MDgyNDY2MH0.Z10ce3cWmeTe4SZnt0vTiCuBMkH8-shZ_BKyZYlj8CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});